spring:
  application:
    name: real-time-push

  mqtt:
    broker: "tcp://iot.eclipse.org:1883"
    topic: "mqtt/real-time"
    qos: 1
    username: "iot"
    password: "iot"
    clientId: "subClient"

---
server:
  port: 10000
